# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./stdafx.h \
    ./mru.h

#Source files
SOURCES += ./stdafx.cpp \
    ./mru.cpp

