#############################################################################
# Makefile for building: qtpropertybrowser
# Generated by qmake (2.01a) (Qt 4.5.1) on: Thu Aug 6 13:08:17 2009
# Project:  qtpropertybrowser.pro
# Template: subdirs
# Command: /home/frankt/qt/qtsdk-2009.02/qt/bin/qmake -unix -o Makefile qtpropertybrowser.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /home/frankt/qt/qtsdk-2009.02/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-examples

examples/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) examples/ || $(MKDIR) examples/ 
	cd examples/ && $(QMAKE) examples.pro -unix -o $(MAKEFILE)
sub-examples-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) examples/ || $(MKDIR) examples/ 
	cd examples/ && $(QMAKE) examples.pro -unix -o $(MAKEFILE)
sub-examples: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE)
sub-examples-make_default-ordered: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) 
sub-examples-make_default: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) 
sub-examples-make_first-ordered: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) first
sub-examples-make_first: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) first
sub-examples-all-ordered: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) all
sub-examples-all: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) all
sub-examples-clean-ordered: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) clean
sub-examples-clean: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) clean
sub-examples-distclean-ordered: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) distclean
sub-examples-distclean: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) distclean
sub-examples-install_subtargets-ordered: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) install
sub-examples-install_subtargets: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) install
sub-examples-uninstall_subtargets-ordered: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-examples-uninstall_subtargets: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qtpropertybrowser.pro  ../../../qt/qtsdk-2009.02/qt/mkspecs/linux-g++/qmake.conf ../../../qt/qtsdk-2009.02/qt/mkspecs/common/g++.conf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/common/unix.conf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/common/linux.conf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/qconfig.pri \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/qt_config.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/default_pre.prf \
		common.pri \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/release.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/default_post.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/warn_on.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/qt.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/moc.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/resources.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/uic.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/yacc.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/lex.prf \
		../../../qt/qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile qtpropertybrowser.pro
../../../qt/qtsdk-2009.02/qt/mkspecs/common/g++.conf:
../../../qt/qtsdk-2009.02/qt/mkspecs/common/unix.conf:
../../../qt/qtsdk-2009.02/qt/mkspecs/common/linux.conf:
../../../qt/qtsdk-2009.02/qt/mkspecs/qconfig.pri:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/qt_config.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/default_pre.prf:
common.pri:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/release.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/default_post.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/warn_on.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/qt.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/moc.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/resources.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/uic.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/yacc.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/lex.prf:
../../../qt/qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile qtpropertybrowser.pro

qmake_all: sub-examples-qmake_all FORCE

make_default: sub-examples-make_default-ordered FORCE
make_first: sub-examples-make_first-ordered FORCE
all: sub-examples-all-ordered FORCE
clean: sub-examples-clean-ordered FORCE
distclean: sub-examples-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-examples-install_subtargets-ordered FORCE
uninstall_subtargets: sub-examples-uninstall_subtargets-ordered FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

