# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./stdafx.h

#Source files
SOURCES += ./main.cpp \
    ./stdafx.cpp
