# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += arguments.h \
	   atmel.h \
	   commands.h \
	   dfu.h \
	   dfu-bool.h \
           dfu-device.h \
	   intel_hex.h \
	   util.h

#Source files
SOURCES += arguments.c \
	   atmel.c \
	   commands.c \
	   dfu.c \
	   intel_hex.c \
	   util.c

