# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS =

#Source files
SOURCES += main.cpp \
    stdafx.cpp
