# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./stdafx.h \
    ./mru.h \
    ./hatswitchwidget.h \
    ./lcdchar.h \
    ./lcdwidget.h 

#Source files
SOURCES += ./stdafx.cpp \
    ./mru.cpp \
    ./hatswitchwidget.cpp \
    ./lcdwidget.cpp 

#Resource file(s)
RESOURCES += qtcommon.qrc

