# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./eepromdata.h \
    ./generichid.h \
    ./stdafx.h

#Source files
SOURCES += ./eepromdata.cpp \
    ./generichid.cpp \
    ./main.cpp \
    ./stdafx.cpp

#Forms
FORMS += ./generichid.ui

#Resource file(s)
RESOURCES += ./generichid.qrc
