# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./makeeeprom.h \
    ./makeeeprom_global.h \
    ./stdafx.h

#Source files
SOURCES += ./makeeeprom.cpp \
    ./stdafx.cpp
