# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./flip.h \
    ./programmer.h \
    ./stdafx.h

#Source files
SOURCES += ./flip.cpp \
    ./programmer.cpp \
    ./stdafx.cpp
