# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./programmer.h \
    ./stdafx.h

#Source files
SOURCES += ./programmer.cpp \
    ./stdafx.cpp
